# Generated by Django 3.1.7 on 2021-02-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210222_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookevent',
            name='event',
        ),
        migrations.AddField(
            model_name='bookevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
